name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "spongbob"
  comment: "spongebob game"
  url: "https://download131.uploadhaven.com/1/application/zip/lh1eX4RpuOuetzjgjSO7msztNPIm4B2sx5Ss26x7.zip?key=reueyACnyCtulwRFHNZDvQ&expire=1705732217&filename=SpongeBob.SquarePants.The.Cosmic.Shake.v1.0.5.0.Incl.ALL.DLC.zio"
  file_name: "android-studio-ide-201.7042882-windows.exe"
  piece_size: 19 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
